[package]
name = "rdp-cert-wizard"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.9.0"
clap = { version = "4.5.35", features = ["derive"] }
anyhow = "1.0.97"
winreg = "0.55.0"
hex = "0.4.3"
